### ISSUE TITLE
Initial transpile of dav1d

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#1]
Transpile libdav1d and the dav1d CLI tool to Rust using c2rust. This initial version can disable features like assembly as needed to get an initial Rust translation of the library that builds.

**Comment by randomPoison** [comment]
I've pushed an initial fork of dav1d that includes transpiled Rust sources alongside their original C equivalents in 099f2b2. To get it to work, I needed to do a few things:

* Build and install c2rust from immunant/c2rust#814 to work around a bug that was causing the transpile to fail.
* Configure meson with the build options `enable_asm=false` and `bitdepths=['16']`.
* Specifically build the `tools/dav1d` ninja target when generating `compile_commands.json` to avoid transpiling the files in `tests/checkasm` because c2rust cannot currently translate those files.

The full process for doing the transpile is:

```
mkdir build && cd build
meson configure -Denable_asm=false "-Dbitdepths=['16']"
cd ..
bear -- ninja -C build tools/dav1d
c2rust transpile compile_commands.json -b dav1d --overwrite-existing
```

**Comment by kkysen** [comment]
Btw, `meson configure` should generate a `compile_commands.json` on its own, so we wouldn't have to use `bear` and compile.  Though if we want to skip compile commands that don't generate `dav1d` (e.x. `tests/checkasm`), we might have to do it this way anyways.  Does this way still transpile any other non-`checkasm` tests?

Also, there's already a Rust port of `checkasm`, [rust-av/checkasm-rs](https://github.com/rust-av/checkasm-rs), so we should try to use that.

**Comment by randomPoison** [comment]
Doing `bear -- ninja -C build tools/dav1d` doesn't compile any of the tests, so currently none of the tests have been transpiled. That was the main reason for using `bear` instead of the `compile_commands.json` generated by `meson configure`.
