### ISSUE TITLE
Slow access to `struct Av1Filter` data

### ISSUE THREAD

**Issue by fbossen** [memorysafety/rav1d#1173]
The `struct Av1Filter` contains `Atomic` elements. Access to these elements, in particular writes in `fn mask_edges_inter`, appear to be much slower than in the C code. 

`struct Rav1dFrameContext_lf` contains a vector of `Av1Filter`. Whereas multiple threads may read/write different elements of this vector, any single `Av1Filter` element would not be written to by a thread at the same time as another thread accesses the same `Av1Filter` element.

Use of non-`Atomic` elements in `struct Av1Filter` should be considered for performance reasons.

**Comment by kkysen** [comment]
I can split the relaxed `.fetch_or`s into relaxed `.load`s, `|`s, and relaxed `.store`s.  That should get rid of lock instructions.  I'm not sure if this is a location @rinon already looked at, but it should be a simple change that I can make.  I'm pretty sure that without `lock *` instructions, there shouldn't be a perf hit here.

**Comment by fbossen** [comment]
Indeed the `lock *` instructions are the issue AFAICT.

**Comment by fbossen** [comment]
There are also `fetch_and`s in `fn rav1d_loopfilter_sbrow_cols` and more `fetch_or`s in `fn mask_edges_intra` and `fn mask_edges_chroma`

**Comment by kkysen** [comment]
> There are also `fetch_and`s in `fn rav1d_loopfilter_sbrow_cols` and more `fetch_or`s in `fn mask_edges_intra` and `fn mask_edges_chroma`

Okay, I'll fix (remove) all of the relaxed `.fetch_*`es.
