### ISSUE TITLE
Overflows can unsoundly taint length state in `AlignedVec`

### ISSUE THREAD

**Issue by HeroicKatora** [memorysafety/rav1d#1356]
Relates to: https://github.com/memorysafety/rav1d/blob/7d7240943d519288fdc9f2b9532b750bd494bf2f/src/align.rs#L185-L191

The following test _must_ fail as it demonstrates memory unsafety, accessing an array way beyond its possible bounds.

```rust
#[test]
#[should_panic]
fn align_vec_fails() {
    let mut v = AlignedVec::<u16, Align8<[u8; 8]>>::new();
    v.resize(isize::MAX as usize + 2, 0u16);
    assert_eq!(v.as_slice()[isize::MAX as usize], 0);
}
```

The problem occurs in release mode, where no overflow checks are enabled. Code must not depend on overflow for correctness. The Safety comment is just incorrect:

            // SAFETY: We've allocated enough space to write
            // up to `new_len` elements into the buffer.

This is untrue. If the calculation for `new_bytes` overflows, the allocation which actually occurs is much smaller. The fix should be quite small, enforce a limit to the newly requested length such that it never overflows. The case of a zero-sized `T` can be ignored, this will never allocate at all.

I'm intending to create a PR soonish.

**Comment by HeroicKatora** [comment]
Expanding on the memory safety issue by stepping through the test: After resizing `v` the `inner` vector has a length of `1`. This is because `(isize::MAX as usize + 2) * 2` wraps to the result `2usize`. Consequently, the new byte length is calculated as `1`. The following assert succeeds at this point:

```rust
    assert_eq!(v.inner.len(), 1);
```

The allocation consequently has a size of 8 bytes. The method nevertheless continues and the initialization loop offsets the base pointer of the allocation _way_ past those 8 bytes and writes the requested number into each memory. This is already UB. Note that the later access in `as_slice()[isize::MAX as usize]` will *also* wrap in memory but the safety requirement of slices has been violated in the call to `from_raw_parts` so this is not necessarily detected. In any case, sometimes this test produces:

```
Caused by:
  process didn't exit successfully: `/tmp/rav1d/target/release/deps/rav1d-ddebe794449c1390` (signal: 11, SIGSEGV: invalid memory reference)
```

**Comment by Lokathor** [comment]
One possible "quick fix" is the classic `size_of::<T>().checked_mul(new_len).unwrap()`
