### ISSUE TITLE
Support cross-compiling for aarch64

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#14]
We need to support building rav1d for ARM 64 (aarch64). The initial transpile only included code for x86-64, so the first thing we need to do is transpile the code for aarch64 and diff it against the current Rust to find where there's platform specific code. We then need to pull in any aarch64 code that's missing, and put any platform-specific code behind an appropriate `#[cfg]`. See #1 for information about what options where used when doing the initial transpile.

**Comment by thedataking** [comment]
Current status: we can build rav1d for aarch64 (and arm7 too once #24 lands). Still need to do this part:
> pull in any aarch64 code that's missing, and put any platform-specific code behind an appropriate #[cfg]
