### ISSUE TITLE
Make function pointers non-optional

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#140]
A number of structs contain function pointers which are mostly used to point to optimized functions implemented in assembly. These are all wrapped in `Option`s that get initialized to `None` when the struct is constructed, and then later get populated with the function pointers in an initialization method. However, in all cases that we've seen so far, every function pointer seems to have a corresponding default C implementation that may optionally be overridden with an assembly function. So in theory we should be able to remove the `Option` wrapper for these function pointers and instead initialize them directly with the correct default function.

**Comment by kkysen** [comment]
I didn't look at it closely yet, but if it's difficult for some reason to do this, we could also first initialize it to a dummy function pointer that just panics.  That way we still get rid of the `Option`.

**Comment by kkysen** [comment]
This might be more difficult than I thought.  It's not clear where these `fn` ptr fields are initially initialized (not the explicit setting to `Some(fn_ptr)` later), and so I'm guessing they're zero-initialized somewhere far away, possibly something like `calloc`.  As `None` works with default zero initialization, I don't think we can get rid of the `Option`s until we clean things up enough to figure out exactly where the initialization is occurring and change it there.
