### ISSUE TITLE
Move the overflow checks into a new release test profile for testing

### ISSUE THREAD

**Issue by kkysen** [memorysafety/rav1d#155]
Right now in #154, overflow checks are enabled in `--release` mode so that they're enabled in testing, which runs in release mode.  We want this soon so that we can catch any bugs.  But eventually, we don't want the normal release mode to have overflow checks (for performance), but we still want it enabled for testing, so we can create a separate profile, inherited from release that enables overflow checks, and then use that in testing.

**Comment by thedataking** [comment]
Closing since we now run debug builds in CI which should catch overflows. Feel free to reopen if I'm missing something.
