### ISSUE TITLE
Use log crate for debug logging

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#171]
dav1d contains a variety of debug logs, and its own infrastructure for enabling and disabling logging. Currently when we cleanup transpiled code, these are getting converted into `println!` invocations, but it would be more idiomatic to use the [log](https://crates.io/crates/log) crate instead. We may eventually want to replace dav1d's infrastructure for controlling log verbosity with something that integrates better with the log crate, but that doesn't have to happen right away.

**Comment by rinon** [comment]
I looked at the `rav1d_log` function and the logger callback and I think we should replace our logging with Rust formatting and if a C user wants a log callback we just pass the formatted string to that logger callback without varargs.
