### ISSUE TITLE
Fix arm7 builds with assembly enabled

### ISSUE THREAD

**Issue by thedataking** [memorysafety/rav1d#180]
Steps:
- Fix build errors (need to update `build.rs` and fix any linker errors)
- Test arm7 with assembly enabled in CI

**Comment by thedataking** [comment]
One step that needs to complete before this issue is closed: transpile/port `wiener_filter_neon` and its callees.

**Comment by kkysen** [comment]
> One step that needs work before this issue is resolved: transpile `wiener_filter_neon` and its callees.

Note: We need to remember to manually transpile the `ALIGN_STK_16` on `mid` as `Align16` when we do transpile `wiener_filter_neon`.
