### ISSUE TITLE
Test rav1d against Argon test vectors

### ISSUE THREAD

**Issue by thedataking** [memorysafety/rav1d#214]
- Argon test vectors [download link](https://storage.googleapis.com/downloads.aomedia.org/assets/zip/argon_coveragetool_av1_base_and_extended_profiles_v2.1.1.zip). More info [here](https://aomedia.org/av1-video-decoder-verification-tool/).
- This takes a long time so we might want to schedule this as an overnight job.
- Run this for x86-64 only or for other targets as well?
- Blocked on #213
- dav1d contains a helpful script `tests/dav1d_argon.bash` that we might want to cherry pick into this repo.

**Comment by fbossen** [comment]
Running `dav1d_argon.bash` takes about 4 minutes on my test machine with the default settings. If testing all `cpumask` values, it's probably closer to half an hour. Interestingly I didn't run into #213

**Comment by kkysen** [comment]
If it only takes ~4 minutes, I can run it locally before every PR at least.  I'm not sure how much slower CI is.

**Comment by fbossen** [comment]
4 minutes was observed on an 8-core machine. I can actually get it down to 100 seconds when processing multiple test streams in parallel with `-j 16`

**Comment by thedataking** [comment]
>  I'm not sure how much slower CI is.
> 4 minutes was observed on an 8-core machine.

The CI machines are substantially slower since we only get two (virtual) CPUs. Here is an example https://github.com/memorysafety/rav1d/actions/runs/4893817220 

- debug w/assembly takes 1h12m
- release w/o assembly takes 32m

This is when passing `-j $NUM_vCPU` to `dav1d_argon.bash` IIRC. The CI builds also need time to download and unpack or cache the tests. Once I hook up a self-hosted runner to test AVX512, we can try switch to running Argon for each PR.

> Interestingly I didn't run into https://github.com/memorysafety/rav1d/issues/213

Interesting indeed. I hit it reliably on the 12-core Ryzen 5900X we're using. Same when building the C sources.
