### ISSUE TITLE
Clean up control flow where c2rust emitted state machines

### ISSUE THREAD

**Issue by thedataking** [memorysafety/rav1d#23]
Grep for `match current_block_` to find instances of this pattern. One can look at the original C code to determine the ideal mapping into structured control flow in Rust. There seem to be 19 instances across 8 files.

**Comment by randomPoison** [comment]
The following files/functions still have state machine control flow that needs to be cleaned up:

* [ ] `cdef_apply.rs` - `rav1d_cdef_brow`
* [ ] `recon.rs` - `decode_coefs`
* [ ] `thread_task.rs` - `reset_task_cur`
* [ ] `thread_task.rs` - `insert_tasks`
* [ ] `thread_task.rs` - `check_tile`

The following ALSO have state machine control flow, but are lower priority:

* [ ] `seek_stress.rs` - `main_0`
* [ ] `ivf.rs` - `ivf_seek`
* [ ] `y4m2.rs` - `y4m2_write`
* [ ] `yuv.rs` - `yuv_write`

**Comment by kkysen** [comment]
The latter ones are not in the `rav1d` library.  They have pretty much zero priority.
