### ISSUE TITLE
Deduplicate code

### ISSUE THREAD

**Issue by kkysen** [memorysafety/rav1d#26]
The transpiled code contains a ton of duplicated code, which can be split into a few categories:

* [x] Deduplicate `rav1d` function prototype declarations (`extern` imports) into proper `use` imports.
* [x] Deduplicate non-`rav1d` (e.x. `libc`, etc.) function prototype declarations (`extern` imports) into a single `extern` block (perhaps one per shared library).
* [x] Deduplicate `rav1d` types from headers.
* [x] Deduplicate non-`rav1d` types from headers into a single, new module.  These seem to mostly be std types.
* [x] Deduplicate `rav1d` constants from headers.
* [x] Deduplicate non-`rav1d` constants from headers.
* [x] #9: Deduplicate inline functions from headers.
* [ ] Deduplicate expanded macros (if possible, rewrite them as functions in C first).
* [ ] #25: Deduplicate templates files.

**Comment by kkysen** [comment]
Does this make sense for duplicated code, and are there any categories I'm missing?  If they look good, I'll turn them each into separate issues and start working on each of them.

Also, what order should I work on them?  Does it matter?  I'm inclined to do them in roughly the order listed above, but not for any particular reason I think.  The exception is newtypes, which I think need to be done before functions, as otherwise those will be considered different types.  Another consideration is if types and function definitions are deduplicated before function prototype declarations, should their imports be turned into more `extern` imports or `use` imports?

**Comment by randomPoison** [comment]
This is effectively done except for #25, which is in review. I'm closing this one now that the remaining work is tracked elsewhere.
