### ISSUE TITLE
Backport test-data fix

### ISSUE THREAD

**Issue by anotherwon** [memorysafety/rav1d#275]
https://github.com/memorysafety/rav1d/blob/0cc86ed188de12b1cf51b038e6f9fa351a560999/tests/dav1d-test-data/10-bit/argon/meson.build#L28-L30

Fixed upstream
https://code.videolan.org/videolan/dav1d-test-data/-/commit/dc72df56c05be149cd888227c3226a201ea3d1cb

**Comment by kkysen** [comment]
@randomPoison, can you take a look at this?  I'm not sure what you did with `dav1d-test-data` in 81eb58aa8 and how to update that to a newer commit.  It doesn't seem to be a submodule.
