### ISSUE TITLE
Performance regression after #438

### ISSUE THREAD

**Issue by fbossen** [memorysafety/rav1d#455]
A significant performance regression was observed after merging #438 when assembly is not used (i.e., disabled at either compile or run time).

A substantial amount of time is newly spent in `core::array::drain::drain_array_with` which is called from `rav1d::src::mc::prep_8tap_rust`

**Comment by fbossen** [comment]
I submitted #457 to address this. Not sure I understand why it makes a difference.

**Comment by kkysen** [comment]
> I submitted #457 to address this. Not sure I understand why it makes a difference.

Thanks!  I have no idea why it makes such a difference either.  I would've thought the by value iterator might be slightly easier to optimize since it's just an integer, but I guess it's the opposite.

How did you realize that would fix it?  Or you just tried some things?

**Comment by fbossen** [comment]
I tracked down the commit that introduced the performance change. Thankfully it was a very small commit, so just tried a few variations. It would be nice to understand whether it's something related to the compiler or something more fundamental related to Rust.

**Comment by kkysen** [comment]
> I tracked down the commit that introduced the performance change. Thankfully it was a very small commit, so just tried a few variations.

I'm glad my little commits paid off for once ☺️.

> It would be nice to understand whether it's something related to the compiler or something more fundamental related to Rust.

I'd guess it's some compiler thing, but we can check.  It'd helpful to know what to avoid in the future.
