### ISSUE TITLE
Decoding hangs when using multiple threads

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#5]
When running the Rust `dav1d` executable it hangs in [`dav1d_parse_obus`](https://github.com/memorysafety/rav1d/blob/099f2b2011d927f6a047dae4c5e900c8e093d75c/src/obu.rs#L5017). It appears to get stuck waiting on a condvar.

Example invocation that hangs, using one of the test data files:

```
cargo run -- -i tests/dav1d-test-data/10-bit/argon/test5606.obu -o out.md5
```

Currently this can be worked around by specifying `--threads 1` when running the CLI.

**Comment by thedataking** [comment]
Related PR #8. Unfortunately, decoding still hangs after fixing (hopefully) all calls to `atomic_xadd`.
