### ISSUE TITLE
Backport: Reduce the size of some public structs

### ISSUE THREAD

**Issue by kkysen** [memorysafety/rav1d#505]
We should backport https://code.videolan.org/videolan/dav1d/-/merge_requests/1540.  This reduces the size of a bunch of the public types, so our conversions will be faster/smaller, and it makes many of them more Rusty, to the point where we can make the `Rav1d*` and `Dav1d*` types the same for some of them (e.x. `Dav1dContentLightLevel`).

This also means we will target compatibility with [`DAV1D_API_VERSION`](https://github.com/memorysafety/rav1d/blob/05daedaa975ca87f39160566442a7199f0ff4836/meson.build#L33-L37) `7.0.0`.

For `Rav1d*` types that haven't been rustified yet, we should backport these changes to the `Rav1d*` types, too.

**Comment by thedataking** [comment]
> This also means we will target compatibility with dav1d 7.0.0.

I'm confused. Isn't dav1d currently on version 1.2.1?

**Comment by kkysen** [comment]
> > This also means we will target compatibility with dav1d 7.0.0.
> 
> I'm confused. Isn't dav1d currently on version 1.2.1?

Hmm, I might've misread that.  They updated the version of something.  It might be supposed to be `dav1d` 1.3.0 instead.

**Comment by kkysen** [comment]
> > This also means we will target compatibility with dav1d 7.0.0.
> 
> I'm confused. Isn't dav1d currently on version 1.2.1?

@thedataking, I think there's a separate `DAV1D_API_VERSION` from the `dav1d` version.  We're currently on `6.8.0` (see [`meson.build`](https://github.com/memorysafety/rav1d/blob/05daedaa975ca87f39160566442a7199f0ff4836/meson.build#L33-L37))
