### ISSUE TITLE
Replace C atomics with Rust equivalents

### ISSUE THREAD

**Issue by rinon** [memorysafety/rav1d#638]
In trying to make Rav1dFrameContext safe I noticed that much of the mutable access we need is actually for fields that are atomic and therefore have inner mutability. Replacing these atomics will give us a better view into what parts of the higher-level context structures can be immutable.

**Comment by kkysen** [comment]
Are you working on this now?  I've been meaning to do this for a while but never got around to it yet.

**Comment by rinon** [comment]
Haven't started yet, I could. There's a lot of complexity around locking hidden in here so we should split this up into smaller chunks of work.

**Comment by kkysen** [comment]
As far as replacing atomic intrinsics with the `Atomic*` types, what's the complexity?  I thought that translation was pretty straightforward and one-to-one.  I know the locking is complex, but I thought just removing the atomic intrinsics would be simple.

**Comment by rinon** [comment]
Guessing they will need to go hand in hand. Maybe not though! The atomic types should be the easier part if we can separate them. But without locking in some structures we don't win much because we still need mutability that we shouldn't.

**Comment by kkysen** [comment]
It's still a significant win on its own I think.  All of the atomic intrinsics are `unsafe` and are unstable as well.
