### ISSUE TITLE
Handle context structure interdependence

### ISSUE THREAD

**Issue by rinon** [memorysafety/rav1d#695]
Rav1d uses three main context structures: `Rav1dContext`, `Rav1dFrameContext`, and `Rav1dTaskContext`. These three structures contain pointers to each other, so there is no valid lifetime to convert these pointers into owned structures and references. Specifically we have the following links:

`Rav1dContext` owns `Rav1dFrameContext`s and `Rav1dTaskContext`s.
`Rav1dFrameContext` has a reference to its parent, `Rav1dContext`.
`Rav1dTaskContext` has a reference to its parent, `Rav1dContext` and to its corresponding `Rav1dFrameContext`.

(there is also a `Rav1dDSPContext` pointer in `Rav1dFrameContext` which is owned by `Rav1dContext`, but that is probably easier to deal with)

I've been investigating options, and I think the most viable is to make `Rav1dContext` an `Arc` and hold a copy of the pointer in the other contexts. This leaves the Task -> Frame pointer, which could either be the same or it could be an index. I need to see what the impact of making that pointer an index might be. If we don't use it that much, that could be an acceptable solution.

Other options: borrow and pass both the `Rav1dContext` and the relevant other context everywhere. This is complicated by the fact that we might want mutable borrows of the contexts.

**Comment by kkysen** [comment]
Do the `Arc<Rav1dContext>`s in `Rav1d{Frame,Task}Context` need to be `Weak` pointers?

Overall, I think this sounds good.  If perf is a concern later, we can investigate removing this `Arc` and passing the `Rav1dContext` in more places, but if this seems like the easier approach for now, that's good.

> (there is also a `Rav1dDSPContext` pointer in `Rav1dFrameContext` which is owned by `Rav1dContext`, but that is probably easier to deal with)

That should be easy to deal with.  `Rav1dDSPContext` can be created by a `const fn` from the CPU flags, so it could just be in a `OnceLock`/`OnceCell`.

**Comment by rinon** [comment]
Turns out I can't do what I wanted, unless I stick the Context in a Mutex or RwLock, which I don't want to do. I'm going to try passing multiple context references instead of linking them

**Comment by randomPoison** [comment]
@rinon Attempted to put `Rav1dContext` into an `Arc` to resolve this, but that caused issues because now the entire context object needs to be read-only.

Now he's experimenting with passing both a `Rav1dContext` and a `Rav1dFrameContext` to places where we used to only pass the `Rav1dFrameContext`. This allows us to remove the `Rav1dContext` pointer from `Rav1dFrameContext` and pass it separately, which resolves the self-referential pointers problem.

**Comment by rinon** [comment]
I've removed the `Rav1dContext` pointer from frame (#718) and task (#721) contexts. I now need to remove the link from Task to Frame contexts.
