### ISSUE TITLE
Cleanup c2rust output in recon.rs

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#703]
* [ ] Cleanup state machine control flow (`current_block` and friends) in `decode_coefs`.
* [ ] Cleanup helper functions to take safe arguments where possible (may take raw  pointers as arguments currently).
* [ ] General cleanup of c2rust generated code in functions.
* [ ] Restore comments from original C.

The following functions still need to be cleaned up:

- [ ] `decode_coefs`
- [ ] `read_coef_tree`
- [ ] `mc`
- [ ] `obmc`
- [ ] `warp_affine`
- [ ] `rav1d_recon_b_intra`
- [ ] `rav1d_recon_b_inter`
- [ ] `rav1d_filter_sbrow_deblock_rows`
- [ ] `rav1d_filter_sbrow_resize`

**Comment by kkysen** [comment]
@thedataking, not sure if you're working on this other than cleaning up the state machines, but I'm cleaning up a bunch in `recon.rs` since I need it to make `refmvs` stuff safe, which I need to make the mvs `Rav1dRef`s `Arc`s.

**Comment by kkysen** [comment]
* Fixed by #1189.
