### ISSUE TITLE
Cleanup c2rust output in lib.rs

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#705]
This file contains the boundary between the C and Rust APIs, so we may still need to make heavy use of unsafe operations in the cleaned up code.

* [x] #707 
* [ ] Cleanup helper functions to take safe arguments where possible (may take raw  pointers as arguments currently).
* [ ] General cleanup of c2rust generated code in functions.
* [ ] Restore comments from original C.

**Comment by randomPoison** [comment]
Looks like this is done as of https://github.com/memorysafety/rav1d/pull/1172.

**Comment by kkysen** [comment]
Oh, this one's not quite done yet.  Should be done in my next PR, though.
