### ISSUE TITLE
Cleanup pointers in structs

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#706]
This is separate from the context pointers, covered in [#695](https://github.com/memorysafety/rav1d/issues/695).

`internal.rs`:

* [x] #707
* [x] #833
* [x] #708
* [x] `Rav1dContext`, `Rav1dContext_refs`, `CdfThreadContext` - Covered by #641
* [x] #709
* [x] #710
* [x] `Rav1dFrameContext_task_thread_pending_tasks` and `Rav1dFrameContext_task_thread`
* [x] #712
* [x] #713
* [x] #714
* [x] #715
* [x] `Rav1dTaskContext_task_thread` - Covered by #696 
* [x] #716
* [x] https://github.com/memorysafety/rav1d/issues/641

`refmvs.rs`:

- [x] #823
- [x] #822

`cdf.rs`

- [x] #824

**Comment by rinon** [comment]
I am working on the TaskThread list currently #802

**Comment by kkysen** [comment]
* Fixed by #706.
