### ISSUE TITLE
`Rav1dContext_intra_edge::root`: Make safe reference type

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#708]
Make the `root` field of `Rav1dContext_intra_edge` into a safe reference type. Currently it is a `[*mut EdgeNode; 2]` that appears to contain pointers to other fields in the `Rav1dContext_intra_edge` struct. Since self-referential fields often don't work well in Rust, we may need to find a different approach to achieve the same goal.

**Comment by kkysen** [comment]
* Fixed by #757.
