### ISSUE TITLE
Test AVX512 instructions in CI

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#74]
We've run into a case where tests fail locally but are not failing in CI (see #71). The issue appears to be specific to AVX512 assembly code, such that tests will fail when run on a machine with AVX512 support, but will pass on a machine without it. This likely means that the default GitHub Actions runners that we're using don't have AVX512 support. We should find a way to test against AVX512 instructions in CI to catch similar issues in the future. If possible, we should continue to run tests against a machine without AVX512 to ensure that the code works correctly with different levels of SIMD support.

**Comment by thedataking** [comment]
Note from discussion on #214 : if we self-host on AVX512-capable machine, we should also try to run Argon on each PR.

**Comment by thedataking** [comment]
We now build and run a single input test on a self-hosted AVX512 capable machine. We could do more so leaving this issue open but feel free to close if others feel this is sufficient.
