### ISSUE TITLE
`fn rav1d_alloc_aligned`: Replace with a safe version for `Vec`s

### ISSUE THREAD

**Issue by kkysen** [memorysafety/rav1d#744]
`fn rav1d_alloc_aligned` is used in many places to allocate a `Vec<_>`/`Box<[_]>` type with an increased alignment.  However, `#[repr(align(...))]` can't be used here since it leaves extra padding between each element.

Here are the current uses of `fn rav1d_alloc_aligned` (alloc align is the alignment specified in `rav1d_alloc_aligned` and align is the natural alignment of the type):

| alloc align | align | size  | size % alloc align | type                              | field                    |
| ----------- | ----- | ----- | ------------------ | --------------------------------- | ------------------------ |
|          64 |     1 |     1 |                  1 | `[DynCoef]`                       | `f.frame_thread.cf`      | 
|          32 |    32 | 14624 |                  0 | `[Rav1dTileState]`                | `f.ts`                   | 
|          64 |     1 |    48 |                 48 | `[[[u16; 8]; 3]]`                 | `f.frame_thread.pal`     | 
|          64 |     1 |     1 |                  1 | `[u8]` => `[Align64<[u8; 64]>]`   | `f.frame_thread.pal_idx` | 
|          32 |     1 |     1 |                  1 | `[u8]`                            | `f.lf.cdef_line_buf`     | 
|          64 |     1 |     1 |                  1 | `[u8]`                            | `f.lf.lr_line_buf`       | 
|          64 |     1 |     1 |                  1 | `[DynPixel]`                      | `f.ipred_edge[0]`        | 
|          64 |     8 | 22680 |                 24 | `Rav1dContext`                    | `c_out`                  | 
|          32 |    16 |  4608 |                  0 | `[Rav1dFrameContext]`             | `c.fc`                   | 
|          64 |       |       |                    | `[c_void]` + `Rav1dMemPoolBuffer` | `data`                   | 
|          64 |     4 |    12 |                 12 | `[refmvs_block]`                  | `rf.r`                   | 
|          64 |     1 |     5 |                  5 | `[refmvs_temporal_block]`         | `rf.rp_proj`             | 

Of these, the ones with `size % alloc align == 0` can add `#[repr(align(alloc align))]` without incurring extra padding in a slice.  Also, `Rav1dContext` is not a slice at all, so no extra padding will be incurred, so it can safely be `#[repr(align(alloc align))]`ed also.  It is also large enough that if a `[Rav1dContext]` were made, the `64 - 22680 % 64 = 48` extra bytes of padding is negligible.

The others are trickier, however.  I looked into `f.frame_thread.pal_idx`, and it could be made into a `[Align64<[u8; 64]>` fairly easily, but for other types, this can be much trickier.

One way of easily solving this is with custom allocators using `#![feature(allocator_api)]`, but this is `nightly`-only and unstable.  Perhaps it's worth it, though?  At least until we get other things safe.  This is how an implementation could look, borrowed from https://stackoverflow.com/questions/69542979/how-can-i-align-memory-on-the-heap-in-a-box-in-a-convenient-way:

```rust
#![feature(allocator_api)]

use std::alloc::AllocError;
use std::alloc::Allocator;
use std::alloc::Global;
use std::alloc::Layout;
use std::ptr::NonNull;

struct AlignedAlloc<const N: usize>;

/// # Safety
/// 
/// Delegates to [`Global`] and only increases the alignment.
unsafe impl<const N: usize> Allocator for AlignedAlloc<N> {
    fn allocate(&self, layout: Layout) -> Result<NonNull<[u8]>, AllocError> {
        Global.allocate(layout.align_to(N).unwrap())
    }

    unsafe fn deallocate(&self, ptr: NonNull<u8>, layout: Layout) {
        Global.deallocate(ptr, layout.align_to(N).unwrap())
    }
}
```

With that, we can do things like this:

```rust
fn f() -> Vec<u8, AlignedAlloc::<64>> {
    Vec::new_in(AlignedAlloc::<64>)
}
```

Compared to the approach in #732 with `AlignedVec64<T>`, this
* does not require that `T: Copy` (`Rav1dTileState`, `Rav1dFrameContext`, etc. aren't)
* is pretty trivially safe
* is const generic, so we don't need to copy `AlignedVec64` to a `AlignedVec32`, etc.
* `AlignedVec64` needs much stricter bounds on `T` to be sound, so it'll be trickier to make it sound vs. `AlignedAlloc`

**Comment by randomPoison** [comment]
From our discussion of this issue: We likely don't need drop support since we can likely manually align the larger non-`Copy` structures (`Rav1dTileState`, `Rav1dContext`, and `Rav1dFrameContext`), either by making them a `Vec<Align64<T>>` or by directly putting the `repr(align)` attribute on the struct directly.

**Comment by kkysen** [comment]
Fixed with `AlignedVec<T, C>`s or `#[repr(align(N))]`s.
