### ISSUE TITLE
Make mode tree node access safe

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#756]
The node tree stored in `Rav1dContext_intra_edge` is currently largely initialized and accessed by passing around raw pointers to its data.

`ModeSelMem` holds onto raw node pointers and should be updated to use safe operations. `ModeSelMem` appears to only be used during initialization, so it shouldn't be an issue to use a less performant but safe approach.

`EdgeBranch::split` contains `*mut EdgeNode`s. We may need to turn these into indices to make this safe.

A recurring unsafe pattern is to pass around `*const EdgeNode`, which points to the first field of an `EdgeBranch` or an `EdgeTip`. The `*const EdgeNode` is then "upcast" to either `*const EdgeBranch` or `*const EdgeTip`. Some examples of this are in `init_edges` and `decode_sb`. We'll need to find an alternate way to express this in safe Rust.

**Comment by kkysen** [comment]
I think `Rav1dContext_intra_edge` can be fully initialized as a `const`.
