### ISSUE TITLE
rav1d fails to build on aarch64

### ISSUE THREAD

**Issue by negge** [memorysafety/rav1d#773]
I tried to build rav1d on aarch64 and get the following error:

```
# cargo build --release
error: cannot produce proc-macro for `atomig-macro v0.3.0` as the target `aarch64-unknown-linux-gnu` does not support these crate types
```

This is using the latest rust on Ubuntu `rustc 1.76.0-nightly (6b771f6b5 2023-11-15)`

**Comment by kkysen** [comment]
What OS are you encountering this on?  I don't think it's an issue with `aarch64-unnknown-linux-gnu` in general, since @fbossen has been compiling and running `rav1d` on `aarch64-unnknown-linux-gnu` on macOS.  Perhaps it is an issue with `+crt-static` and static linking (https://github.com/rust-lang/rust/issues/78210)?

**Comment by fbossen** [comment]
I am running into the same issue as @negge on a Raspberry Pi with Ubuntu 22.04. As @kkysen points out, no such issue on macOS for `aarch64`.

**Comment by fbossen** [comment]
@negge I seem to have better luck with `cargo build --release --target aarch64-unknown-linux-gnu`

**Comment by rinon** [comment]
This might be an issue with atomig itself: https://docs.rs/atomig/latest/atomig/#notes. We don't really need this dependency, so we should probably just replace it.

**Comment by fbossen** [comment]
> This might be an issue with atomig itself: https://docs.rs/atomig/latest/atomig/#notes ("This has the unfortunate effect that this whole library will fail to compile on any targets where any of the atomic methods/types are unavailable."). We don't really need this dependency, so we should probably just replace it.

Not sure the issue is with `atomig` itself. The same issue was present earlier with `paste`

**Comment by negge** [comment]
> @negge I seem to have better luck with `cargo build --release --target aarch64-unknown-linux-gnu`

Thanks @fbossen, I was able to build the project with that command line.

**Comment by kkysen** [comment]
@negge, we figured out that our `.cargo/config.toml` with `rustflags` set to `-C target-feature=+crt-static` was the issue.  We had added that to cross-compile and run with qemu, and we're trying to figure out how to support both qemu and normal builds.  In the meantime, manually specifying `--target aarch64-unknown-linux-gnu` should work as @fbossen pointed out.

**Comment by LukasKalbertodt** [comment]
The error message in the top comment suggests that this has nothing to do with any atomic operations, but with the fact that `proc-macro` crates are not supported in certain build/target configurations. There seems to be a solution to this issue now, but to throw out another way to fix this: you can remove the `derive` feature from `atomig` and replace [these derives of `Atom` and `AtomLogic`](https://github.com/memorysafety/rav1d/blob/ed341e1a826998b44bbf3562272f18266dac8c47/src/picture.rs#L50) with manual impls:

```rust
impl atomic::Atom for PictureFlags {
    type Repr = u8;
    fn pack(self) -> Self::Repr { self. 0 }
    fn unpack(src: Self::Repr) -> Self { Self(src) }
}
impl atomic::AtomLogic for PictureFlags {}
```
