### ISSUE TITLE
Cleanup c2rust output in `itx.rs`

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#817]
Note that this should wait until after #683 is merged in order to not duplicate work between the 8bpc and 16bpc versions.

* [ ] Cleanup helper functions to take safe arguments where possible (may take raw pointers as arguments currently).
* [ ] General cleanup of c2rust generated code in functions.
* [ ] Restore comments from original C.

The following functions still need to be cleaned:

- [x] `inv_txfm_add_wht_wht_4x4_rust`

**Comment by kkysen** [comment]
> I'm working on deduplicating and cleaning up this module in PR #683 so I can do this one unless someone else wants to.

@thedataking, have you actually started this?  I can do this.  I started doing `itx_1d` but they overlap a lot

**Comment by randomPoison** [comment]
Looks like this was finished in #1042, and the module has been made fully safe as of #1143, so I'm going to close this.
