### ISSUE TITLE
`struct refmvs_frame`: Make fields safer without changing layout

### ISSUE THREAD

**Issue by randomPoison** [memorysafety/rav1d#822]
Also cleanup `rav1d_refmvs_init` and `rav1d_refmvs_clear`.

- [x] `frm_hdr` - Pointer to `f.frame_hdr`. We may be able to pass `frame_hdr` into the places where it's used. `frm_hdr` is only used from `rav1d_refmvs_find` and `add_temporal_candidate`, which is only called from `rav1d_refmvs_find`. So if we can pass `f.frame_hdr` into `rav1d_refmvs_find` and then down into `add_temporal_candidate` we should be able to remove this field.  Since `frm_hdr` is not used by `load_tmvs_c` (and thus not accessed by asm), we should change it to a `*const ()`, signifying that it should never be used while keeping the layout the same.  It is dangerous to keep it as a `*const Rav1dFrameHeader`, since it's a `*const Dav1dFrameHeader` in C.  And passing the `&Rav1dFrameHeader` through the callstack removes the lifetime issue as well.
- [x] `rp` - Points to `f.mvs`.  `rp` is also not accessed in `load_tmvs_c`, so hopefully we can change it (in a layout preserving manner).

**Comment by fbossen** [comment]
There may be a conflict with #821 where a pointer to a `struct refmvs_frame` is passed to an asm function.

**Comment by randomPoison** [comment]
Ah, that's a good point. Even before #821 `refmvs_frame` is being passed into asm functions, so I'm not sure we can actually make changes to it safely. The sister struct `refmvs_tile` seems to only be used from Rust so I think we can still clean that one up.

**Comment by kkysen** [comment]
I think we should do part of this.  At least, `frame_hdr` should be made a `*const ()` and passed separately as a reference through the callstack as @randomPoison proposed above.  It seems dangerous to leave a `*const Rav1dFrameHeader` when C has a `*const Dav1dFrameHeader`.  We can make `refmvs_frame` safer; we just can't change its layout at all, and we can't fields that are accessed in `load_tmvs_c`.  See also https://github.com/memorysafety/rav1d/pull/821#discussion_r1529542020.

**Comment by kkysen** [comment]
* Fixed by #983.

**Comment by kkysen** [comment]
* Fixed by #983.
