### ISSUE TITLE
Replace all `printf`s with `print!`/`println!`

### ISSUE THREAD

**Issue by kkysen** [memorysafety/rav1d#865]

**Comment by folkertdev** [comment]
does this include the `tools/` or just `src/recon.rs` (the only file I can find with a `use libc::printf`)

**Comment by kkysen** [comment]
> does this include the `tools/` or just `src/recon.rs` (the only file I can find with a `use libc::printf`)

`tools/` doesn't really matter, just stuff in `librav1d`.  That might just be `recon.rs` if that's all You've found.
