### ISSUE TITLE
tests fail to link

### ISSUE THREAD

**Issue by folkertdev** [memorysafety/rav1d#873]
I think a recent commit broke something that causes linker errors when running the tests for me. `git bisect` points to https://github.com/memorysafety/rav1d/commit/3bf213cde9c03fa8f13782445d1a1081cde8b176 as the cause. I'm on an x86_64 linux machine, and running the tests works fine before this commit.

```
folkertdev@folkertdev ~/r/r/build ((3bf213cd…)|BISECTING) [125]> cargo build --release && meson test \
                                                                   --suite testdata-8 \
                                                                   --suite testdata-10 \
                                                                   --suite testdata-12 \
                                                                   --suite testdata-multi
ninja: Entering directory `/home/folkertdev/rust/rav1d/build'
[2/3] Linking target tools/dav1d.
FAILED: tools/dav1d 
cc  -o tools/dav1d 'tools/f9d35d4@@dav1d@exe/dav1d.c.o' 'tools/f9d35d4@@dav1d@exe/dav1d_cli_parse.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group librav1d.a tools/libdav1d_input.a tools/libdav1d_output.a -pthread -lm -Wl,--end-group '-Wl,-rpath,$ORIGIN/..:$ORIGIN/' -Wl,-rpath-link,/home/folkertdev/rust/rav1d/build/ -Wl,-rpath-link,/home/folkertdev/rust/rav1d/build/tools
/usr/bin/ld: librav1d.a(std-eb8a07e9874efeeb.std.ee38bba0a237925c-cgu.0.rcgu.o): in function `std::sys::unix::weak::fetch':
/rustc/6b771f6b5a6c8b03b6322a9c77ac77cb346148f0/library/std/src/sys/unix/weak.rs:138: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
[3/3] Linking target tests/seek_stress.
FAILED: tests/seek_stress 
cc  -o tests/seek_stress 'tests/59830eb@@seek_stress@exe/seek_stress.c.o' 'tools/f9d35d4@@dav1d@exe/dav1d_cli_parse.c.o' 'tools/f9d35d4@@dav1d_input@sta/input_input.c.o' 'tools/f9d35d4@@dav1d_input@sta/input_ivf.c.o' -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group librav1d.a -pthread -lm -Wl,--end-group '-Wl,-rpath,$ORIGIN/..' -Wl,-rpath-link,/home/folkertdev/rust/rav1d/build/
/usr/bin/ld: librav1d.a(std-eb8a07e9874efeeb.std.ee38bba0a237925c-cgu.0.rcgu.o): in function `std::sys::unix::weak::fetch':
/rustc/6b771f6b5a6c8b03b6322a9c77ac77cb346148f0/library/std/src/sys/unix/weak.rs:138: undefined reference to `dlsym'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
Could not rebuild /home/folkertdev/rust/rav1d/build
```

tagging @thedataking

**Comment by thedataking** [comment]
Thanks for the heads up; I'm having trouble reproducing on `main` with meson 0.61.2 on Ubuntu LTS 22.02.

Starting from a clean checkout, I run `mkdir build && cd build && meson setup ..` before I run your command.

We usually rely on the `test.sh` script for testing:

```
cargo build --release && .github/workflows/test.sh -r target/release/dav1d -s target/release/seek_stress
```

(This will also run the seek stress tests but of course you can add that to the command you're using too.)

Can you think of any steps I can take to reproduce your issue. I'm wondering if we might be setting up the `build` dir different from each other.

**Comment by folkertdev** [comment]
interesting, that `test.sh` script works fine for me, runs all the tests. Does `test_rust=true` get set when I run `meson test` without further arguments? I removed the `build` directory and recreated it with the command you gave, but the `meson test` command still fails in the same way.

My meson is a little older but that I don't see why that would matter. Maybe the fix here is to have the README point to that `test.sh` file instead of the manual meson command?

btw running just 

```
cargo build --release && .github/workflows/test.sh -r target/release/dav1d
```

without the stress tests will fail until you run with the stress tests once,  the error is 

```
tests/meson.build:158:8: ERROR: File ../ does not exist.
```

which is this line (I guess the `get_option` just gives the empty string?)

```
        seek_stress = files(join_paths('../', get_option('seek_stress_test_rust_path')))
```

I think that path gets created the first time you do run with the stress tests? That'll work fine on CI etc but would be nice to fix if it becomes the general solution.
